environment:

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python310"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      PYTHON: "Python3.10"
 #     APPVEYOR_SSH_KEY:

    - APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma
      PYTHON: "Python3.10"

build: off

install:
  - cmd: echo "     ** windows build **"
  - sh: if [[ $(uname -s) == Linux ]]; then echo "     ** linux build **"; fi
  - sh: if [[ $(uname -s) == Darwin ]]; then echo "     ** macos build **"; fi

#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

  - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - sh: if [[ $PYTHON == Python3.10 ]]; then export PATH=~/venv3.10/bin:~/venv3.10/lib:$PATH; fi

  - python --version
  - python -m pip install pip --upgrade
  - pip -V
  - pip install setuptools --upgrade
  - pip install pytest
  - pip install -e .[server]
  - sh: if [[ $(uname -s) == Linux ]]; then pip3 install coverage[toml]; fi

  # Install SQLite 3.38 or later (only for Linux)
  - sh: |
      if [[ $(uname -s) == Linux ]]; then
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        wget https://www.sqlite.org/2024/sqlite-autoconf-3380000.tar.gz
        tar -xvzf sqlite-autoconf-3380000.tar.gz
        cd sqlite-autoconf-3380000
        ./configure
        make
        sudo make install
        sqlite3 --version
      fi
#  - sh: export APPVEYOR_SSH_BLOCK=true
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

test_script:
  - cmd: python -m populse_db.test -v
  - sh: if [[ $(uname -s) == Darwin ]]; then python -m populse_db.test -v; fi
  - sh: if [[ $(uname -s) == Linux ]]; then coverage run --source=populse_db -m pytest -v; fi
  - sh: if [[ $(uname -s) == Linux ]]; then coverage xml -i; fi

after_test:
  - sh: if [[ $(uname -s) == Linux ]]; then curl -Os https://uploader.codecov.io/latest/linux/codecov; fi
  - sh: if [[ $(uname -s) == Linux ]]; then chmod +x codecov; fi
  - sh: if [[ $(uname -s) == Linux ]]; then ./codecov -f "coverage.xml" -t "b88bf18b-b29e-412e-96fe-e0f00832c173"; fi

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
